### ISSUE TITLE
13#The 2FOR12012 code is no longer valid. We offer 4FOR32018 instead. In addition, please tell the customer that this coupon code and can be redeemed only on site (priority = high).

### ISSUE THREAD

**Issue by lyw1024** [markxiaotao/05Restaurant#13]
The 2FOR12012 code is no longer valid. We offer 4FOR32018 instead. In addition, please tell the customer that this coupon code and can be redeemed only on site (priority = high).

**Comment by Gavin-23** [comment]
i have changed to changed code to 4FOR32018

**Comment by markxiaotao** [comment]
done
